[functions.square-connect-callback]
verify_jwt = false

[functions.stripe-create-checkout-session]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.square-payment-webhook]
verify_jwt = false
